name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Accept SDK licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build with gradle
        run: ./gradlew assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
